#!/bin/bash

umask 002

start_emulator() {
  avd=$1
  pidfile=/tmp/$avd.pid
  echo "Starting emulator"
  daemon -f -p $pidfile `which emulator` -avd $avd -no-window -wipe-data
  sleep 240
  adb push testing/orng /data/orng >/dev/null 2>/dev/null
}

stop_emulator() {
  avd=$1
  pidfile=/tmp/$avd.pid
  kill -9 `cat $pidfile` && rm -f $pidfile
}

GLOBALLOG=/tmp/breviar-nightlies.log
rm -f $GLOBALLOG

(
echo "Running nightlies."
. dir_setup.sh

LOCK=/tmp/breviar-nightlies.lck
(
  if flock -w 5 9; then
    true
  else
    echo "Unable to get lock!"
    exit 1
  fi
  pushd .. >/dev/null

  DATE=`date +%F`
  VERSION=`cat AndroidManifest.xml | grep "android:versionName" | sed "s/.*versionName=\"//;s/\".*//"`

  rm -rf $ROOT/$DATE
  mkdir -p $ROOT/$DATE
  LOG=$ROOT/$DATE/log.txt

  echo "Git fetch and merge."
  if ( git fetch --all && git merge juraj/master ) >>$LOG 2>&1; then
    echo "Git merge successful."
  else
    echo "Git merge failed! Log follows:"
    echo
    cat $LOG
    exit 0
  fi

  COMMIT=`git branch -v --no-abbrev | egrep "^. master" | sed "s/. master *//;s/ .*//"`
  echo $COMMIT >$ROOT/$DATE/commit.txt

  echo "Build. Log file is at <a href=\"https://breviar.kralovic.org/nightlies/$DATE/log.txt\">https://breviar.kralovic.org/nightlies/$DATE/log.txt</a>"
  if (./build-assets && gradle clean && gradle assembleDebug && \
      gradle assembleRelease && gradle bundleRelease ) >>$LOG 2>&1; then
    echo "Build finished successfully."
  else
    echo "Build failed! Log follows:"
    echo
    cat $LOG
    exit 0
  fi

  cp build/outputs/apk/release/android-release.apk $ROOT/$DATE/breviar.apk
  cp build/outputs/bundle/release/android.aab $ROOT/$DATE/breviar.aab
  cp build/outputs/apk/debug/android-debug.apk $ROOT/$DATE/breviar-debug.apk
  echo "Nightly package is at: breviar.kralovic.org:$ROOT/$DATE/breviar.apk"
  echo "Or: https://breviar.kralovic.org/nightlies/$DATE/breviar.apk"
  echo "Nightly bundle is at: breviar.kralovic.org:$ROOT/$DATE/breviar.aab"
  echo "Or: https://breviar.kralovic.org/nightlies/$DATE/breviar.aab"
  echo "Nightly debug package is at: breviar.kralovic.org:$ROOT/$DATE/breviar-debug.apk"
  echo "Or: https://breviar.kralovic.org/nightlies/$DATE/breviar-debug.apk"

  ### Emulator is not that easy on FreeBSD, it has rather heavyweight linux dependencies (e.g. libsystemd, Qt5...)
  #start_emulator android_24

  #echo "Running tests."
  #TEST_LOG=$ROOT/$DATE/test_log
  #mkdir -p $TEST_LOG
  #monkeyrunner testing/run_tests.py $TEST_LOG $DATE $COMMIT $VERSION

  #stop_emulator android_24

  #echo "Test results are available at http://kedrigern.dcs.fmph.uniba.sk/~riso/breviar-testing/nightlies/$DATE/test_log/index.html"
  popd >/dev/null
) 9>$LOCK

rm -f $LOCK
) 2>&1 | tee $GLOBALLOG | mail -s "Breviar nightly" android@breviar.sk videky@breviar.sk
