#!/bin/sh
#sudo /usr/local/bin/build-access.sh && rm -rf bin && ./build-assets && ndk-build && gradle assembleDebug && gradle assembleRelease
./build-assets && gradle assembleDebug && gradle assembleRelease
