tgit mv ord_inv.htm   ord-inv.htm 
tgit mv ord_k0.htm    ord-k0.htm  
tgit mv ord_k1.htm    ord-k1.htm  
tgit mv ord_k2.htm    ord-k2.htm  
tgit mv ord_k3.htm    ord-k3.htm  
tgit mv ord_k4.htm    ord-k4.htm  
tgit mv ord_k5.htm    ord-k5.htm  
tgit mv ord_k6.htm    ord-k6.htm  
tgit mv ord_km.htm    ord-km.htm  
tgit mv ord_komp.htm  ord-komp.htm
tgit mv ord_pc.htm    ord-pc.htm  
tgit mv ord_rch.htm   ord-rch.htm 
tgit mv ord_vesp.htm  ord-vesp.htm
